version: "0.1"
provider:
  github:
    repository: "org/repo-name"
    auth:
      token: "${GITHUB_TOKEN}"

environment:
  # Variables shared across hosts
  global_env:
    - KEY=value
    - PATH=/usr/local/bin:$PATH

# Pool of available machines/servers
hosts:
  - name: test-node-1
    address: 192.168.1.101
    install: # Per-host software bootstrap
      - apt-get update
      - apt-get install -y bison flex
  - name: test-node-2
    address: test.example.com # Can be a local or publicly accessible address
    install:
      - apt-get update
      - apt-get install -y docker git make
  - name: test-node-3
    address: backup.test.example.com

pipeline:
  # build on initalization
  build:
    - name: build-workers
      runs_on: ["test-node-1", "test-node-2", "test-node-3"] # Choose servers to run on
      steps:
        - git clone https://github.com/${github.repository}.git
        - cd /project && go build ./cmd
  # run tasks in parallel, divide them between the hosts
  tasks:
    - name: test-project-with-pattern
      runs_on: ["test-node-1", "test-node-2", "test-node-3"]
      tasks:
        pattern: ".+_test.go" # regex expression
        cmd: go test {file} # this will run each test file found using the pattern

    - name: test-project-with-explicit-files
      runs_on: ["test-node-1", "test-node-2"]
      files: ["check_conn.sh", "permission_test.sh"] # relative to project root.
      cmd: ./{file}
