// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/provider/provider.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RepositoryProvider_Clone_FullMethodName          = "/provider.RepositoryProvider/Clone"
	RepositoryProvider_Fetch_FullMethodName          = "/provider.RepositoryProvider/Fetch"
	RepositoryProvider_CreateWorkTree_FullMethodName = "/provider.RepositoryProvider/CreateWorkTree"
	RepositoryProvider_RemoveWorkTree_FullMethodName = "/provider.RepositoryProvider/RemoveWorkTree"
)

// RepositoryProviderClient is the client API for RepositoryProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoryProviderClient interface {
	Clone(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	Fetch(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	CreateWorkTree(ctx context.Context, in *WorkTreeRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	RemoveWorkTree(ctx context.Context, in *WorkTreeRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type repositoryProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoryProviderClient(cc grpc.ClientConnInterface) RepositoryProviderClient {
	return &repositoryProviderClient{cc}
}

func (c *repositoryProviderClient) Clone(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RepositoryProvider_Clone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryProviderClient) Fetch(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RepositoryProvider_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryProviderClient) CreateWorkTree(ctx context.Context, in *WorkTreeRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RepositoryProvider_CreateWorkTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryProviderClient) RemoveWorkTree(ctx context.Context, in *WorkTreeRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, RepositoryProvider_RemoveWorkTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryProviderServer is the server API for RepositoryProvider service.
// All implementations should embed UnimplementedRepositoryProviderServer
// for forward compatibility.
type RepositoryProviderServer interface {
	Clone(context.Context, *SyncRequest) (*SyncResponse, error)
	Fetch(context.Context, *SyncRequest) (*SyncResponse, error)
	CreateWorkTree(context.Context, *WorkTreeRequest) (*SyncResponse, error)
	RemoveWorkTree(context.Context, *WorkTreeRequest) (*SyncResponse, error)
}

// UnimplementedRepositoryProviderServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRepositoryProviderServer struct{}

func (UnimplementedRepositoryProviderServer) Clone(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedRepositoryProviderServer) Fetch(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedRepositoryProviderServer) CreateWorkTree(context.Context, *WorkTreeRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkTree not implemented")
}
func (UnimplementedRepositoryProviderServer) RemoveWorkTree(context.Context, *WorkTreeRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveWorkTree not implemented")
}
func (UnimplementedRepositoryProviderServer) testEmbeddedByValue() {}

// UnsafeRepositoryProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoryProviderServer will
// result in compilation errors.
type UnsafeRepositoryProviderServer interface {
	mustEmbedUnimplementedRepositoryProviderServer()
}

func RegisterRepositoryProviderServer(s grpc.ServiceRegistrar, srv RepositoryProviderServer) {
	// If the following call pancis, it indicates UnimplementedRepositoryProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RepositoryProvider_ServiceDesc, srv)
}

func _RepositoryProvider_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryProviderServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryProvider_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryProviderServer).Clone(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryProvider_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryProviderServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryProvider_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryProviderServer).Fetch(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryProvider_CreateWorkTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryProviderServer).CreateWorkTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryProvider_CreateWorkTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryProviderServer).CreateWorkTree(ctx, req.(*WorkTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryProvider_RemoveWorkTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryProviderServer).RemoveWorkTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryProvider_RemoveWorkTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryProviderServer).RemoveWorkTree(ctx, req.(*WorkTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoryProvider_ServiceDesc is the grpc.ServiceDesc for RepositoryProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoryProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "provider.RepositoryProvider",
	HandlerType: (*RepositoryProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Clone",
			Handler:    _RepositoryProvider_Clone_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _RepositoryProvider_Fetch_Handler,
		},
		{
			MethodName: "CreateWorkTree",
			Handler:    _RepositoryProvider_CreateWorkTree_Handler,
		},
		{
			MethodName: "RemoveWorkTree",
			Handler:    _RepositoryProvider_RemoveWorkTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/provider/provider.proto",
}
