// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/mq/consume.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumerCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MqUrl         string                 `protobuf:"bytes,1,opt,name=mq_url,json=mqUrl,proto3" json:"mq_url,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerCommandRequest) Reset() {
	*x = ConsumerCommandRequest{}
	mi := &file_proto_mq_consume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerCommandRequest) ProtoMessage() {}

func (x *ConsumerCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_consume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerCommandRequest.ProtoReflect.Descriptor instead.
func (*ConsumerCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_mq_consume_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumerCommandRequest) GetMqUrl() string {
	if x != nil {
		return x.MqUrl
	}
	return ""
}

func (x *ConsumerCommandRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ConsumerCommandRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ConsumerCommandRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ConsumerCommandResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Output          string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	FinishedCommand *bool                  `protobuf:"varint,2,opt,name=finished_command,json=finishedCommand,proto3,oneof" json:"finished_command,omitempty"`
	Error           *ConsumerError         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConsumerCommandResponse) Reset() {
	*x = ConsumerCommandResponse{}
	mi := &file_proto_mq_consume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerCommandResponse) ProtoMessage() {}

func (x *ConsumerCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_consume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerCommandResponse.ProtoReflect.Descriptor instead.
func (*ConsumerCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_mq_consume_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumerCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ConsumerCommandResponse) GetFinishedCommand() bool {
	if x != nil && x.FinishedCommand != nil {
		return *x.FinishedCommand
	}
	return false
}

func (x *ConsumerCommandResponse) GetError() *ConsumerError {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConsumerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumerError) Reset() {
	*x = ConsumerError{}
	mi := &file_proto_mq_consume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerError) ProtoMessage() {}

func (x *ConsumerError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mq_consume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerError.ProtoReflect.Descriptor instead.
func (*ConsumerError) Descriptor() ([]byte, []int) {
	return file_proto_mq_consume_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumerError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_mq_consume_proto protoreflect.FileDescriptor

const file_proto_mq_consume_proto_rawDesc = "" +
	"\n" +
	"\x16proto/mq/consume.proto\x12\x02mq\"\xd8\x01\n" +
	"\x16ConsumerCommandRequest\x12\x15\n" +
	"\x06mq_url\x18\x01 \x01(\tR\x05mqUrl\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12>\n" +
	"\x06params\x18\x03 \x03(\v2&.mq.ConsumerCommandRequest.ParamsEntryR\x06params\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x17ConsumerCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12.\n" +
	"\x10finished_command\x18\x02 \x01(\bH\x00R\x0ffinishedCommand\x88\x01\x01\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.mq.ConsumerErrorR\x05errorB\x13\n" +
	"\x11_finished_command\"'\n" +
	"\rConsumerError\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2^\n" +
	"\x10ConsumerServicer\x12J\n" +
	"\rStartConsumer\x12\x1a.mq.ConsumerCommandRequest\x1a\x1b.mq.ConsumerCommandResponse0\x01B0Z.github.com/ImTheCurse/ConflowCI/internal/mq/pbb\x06proto3"

var (
	file_proto_mq_consume_proto_rawDescOnce sync.Once
	file_proto_mq_consume_proto_rawDescData []byte
)

func file_proto_mq_consume_proto_rawDescGZIP() []byte {
	file_proto_mq_consume_proto_rawDescOnce.Do(func() {
		file_proto_mq_consume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mq_consume_proto_rawDesc), len(file_proto_mq_consume_proto_rawDesc)))
	})
	return file_proto_mq_consume_proto_rawDescData
}

var file_proto_mq_consume_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_mq_consume_proto_goTypes = []any{
	(*ConsumerCommandRequest)(nil),  // 0: mq.ConsumerCommandRequest
	(*ConsumerCommandResponse)(nil), // 1: mq.ConsumerCommandResponse
	(*ConsumerError)(nil),           // 2: mq.ConsumerError
	nil,                             // 3: mq.ConsumerCommandRequest.ParamsEntry
}
var file_proto_mq_consume_proto_depIdxs = []int32{
	3, // 0: mq.ConsumerCommandRequest.params:type_name -> mq.ConsumerCommandRequest.ParamsEntry
	2, // 1: mq.ConsumerCommandResponse.error:type_name -> mq.ConsumerError
	0, // 2: mq.ConsumerServicer.StartConsumer:input_type -> mq.ConsumerCommandRequest
	1, // 3: mq.ConsumerServicer.StartConsumer:output_type -> mq.ConsumerCommandResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mq_consume_proto_init() }
func file_proto_mq_consume_proto_init() {
	if File_proto_mq_consume_proto != nil {
		return
	}
	file_proto_mq_consume_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mq_consume_proto_rawDesc), len(file_proto_mq_consume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mq_consume_proto_goTypes,
		DependencyIndexes: file_proto_mq_consume_proto_depIdxs,
		MessageInfos:      file_proto_mq_consume_proto_msgTypes,
	}.Build()
	File_proto_mq_consume_proto = out.File
	file_proto_mq_consume_proto_goTypes = nil
	file_proto_mq_consume_proto_depIdxs = nil
}
