// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/mq/consume.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsumerServicer_StartConsumer_FullMethodName = "/mq.ConsumerServicer/StartConsumer"
)

// ConsumerServicerClient is the client API for ConsumerServicer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerServicerClient interface {
	StartConsumer(ctx context.Context, in *ConsumerCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumerCommandResponse], error)
}

type consumerServicerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerServicerClient(cc grpc.ClientConnInterface) ConsumerServicerClient {
	return &consumerServicerClient{cc}
}

func (c *consumerServicerClient) StartConsumer(ctx context.Context, in *ConsumerCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConsumerCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConsumerServicer_ServiceDesc.Streams[0], ConsumerServicer_StartConsumer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumerCommandRequest, ConsumerCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerServicer_StartConsumerClient = grpc.ServerStreamingClient[ConsumerCommandResponse]

// ConsumerServicerServer is the server API for ConsumerServicer service.
// All implementations should embed UnimplementedConsumerServicerServer
// for forward compatibility.
type ConsumerServicerServer interface {
	StartConsumer(*ConsumerCommandRequest, grpc.ServerStreamingServer[ConsumerCommandResponse]) error
}

// UnimplementedConsumerServicerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsumerServicerServer struct{}

func (UnimplementedConsumerServicerServer) StartConsumer(*ConsumerCommandRequest, grpc.ServerStreamingServer[ConsumerCommandResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartConsumer not implemented")
}
func (UnimplementedConsumerServicerServer) testEmbeddedByValue() {}

// UnsafeConsumerServicerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServicerServer will
// result in compilation errors.
type UnsafeConsumerServicerServer interface {
	mustEmbedUnimplementedConsumerServicerServer()
}

func RegisterConsumerServicerServer(s grpc.ServiceRegistrar, srv ConsumerServicerServer) {
	// If the following call pancis, it indicates UnimplementedConsumerServicerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsumerServicer_ServiceDesc, srv)
}

func _ConsumerServicer_StartConsumer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumerCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServicerServer).StartConsumer(m, &grpc.GenericServerStream[ConsumerCommandRequest, ConsumerCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConsumerServicer_StartConsumerServer = grpc.ServerStreamingServer[ConsumerCommandResponse]

// ConsumerServicer_ServiceDesc is the grpc.ServiceDesc for ConsumerServicer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsumerServicer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mq.ConsumerServicer",
	HandlerType: (*ConsumerServicerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartConsumer",
			Handler:       _ConsumerServicer_StartConsumer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mq/consume.proto",
}
