// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sync/build.proto

package pb

import (
	pb "github.com/ImTheCurse/ConflowCI/internal/provider/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Req           *pb.SyncRequest        `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	BuildSteps    []string               `protobuf:"bytes,3,rep,name=build_steps,json=buildSteps,proto3" json:"build_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerConfig) Reset() {
	*x = WorkerConfig{}
	mi := &file_sync_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerConfig) ProtoMessage() {}

func (x *WorkerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sync_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerConfig.ProtoReflect.Descriptor instead.
func (*WorkerConfig) Descriptor() ([]byte, []int) {
	return file_sync_build_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerConfig) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *WorkerConfig) GetReq() *pb.SyncRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WorkerConfig) GetBuildSteps() []string {
	if x != nil {
		return x.BuildSteps
	}
	return nil
}

type WorkerBuildOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=WorkerName,proto3" json:"WorkerName,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=Output,proto3" json:"Output,omitempty"`
	Error         *WorkerBuildError      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerBuildOutput) Reset() {
	*x = WorkerBuildOutput{}
	mi := &file_sync_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerBuildOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerBuildOutput) ProtoMessage() {}

func (x *WorkerBuildOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sync_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerBuildOutput.ProtoReflect.Descriptor instead.
func (*WorkerBuildOutput) Descriptor() ([]byte, []int) {
	return file_sync_build_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerBuildOutput) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *WorkerBuildOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WorkerBuildOutput) GetError() *WorkerBuildError {
	if x != nil {
		return x.Error
	}
	return nil
}

type WorkerBuildError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerBuildError) Reset() {
	*x = WorkerBuildError{}
	mi := &file_sync_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerBuildError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerBuildError) ProtoMessage() {}

func (x *WorkerBuildError) ProtoReflect() protoreflect.Message {
	mi := &file_sync_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerBuildError.ProtoReflect.Descriptor instead.
func (*WorkerBuildError) Descriptor() ([]byte, []int) {
	return file_sync_build_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerBuildError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sync_build_proto protoreflect.FileDescriptor

const file_sync_build_proto_rawDesc = "" +
	"\n" +
	"\x10sync/build.proto\x12\x04sync\x1a\x17provider/provider.proto\"y\n" +
	"\fWorkerConfig\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12'\n" +
	"\x03req\x18\x02 \x01(\v2\x15.provider.SyncRequestR\x03req\x12\x1f\n" +
	"\vbuild_steps\x18\x03 \x03(\tR\n" +
	"buildSteps\"y\n" +
	"\x11WorkerBuildOutput\x12\x1e\n" +
	"\n" +
	"WorkerName\x18\x01 \x01(\tR\n" +
	"WorkerName\x12\x16\n" +
	"\x06Output\x18\x02 \x01(\tR\x06Output\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x16.sync.WorkerBuildErrorR\x05error\"(\n" +
	"\x10WorkerBuildError\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error2O\n" +
	"\rWorkerBuilder\x12>\n" +
	"\x0fBuildRepository\x12\x12.sync.WorkerConfig\x1a\x17.sync.WorkerBuildOutputB2Z0github.com/ImTheCurse/ConflowCI/internal/sync/pbb\x06proto3"

var (
	file_sync_build_proto_rawDescOnce sync.Once
	file_sync_build_proto_rawDescData []byte
)

func file_sync_build_proto_rawDescGZIP() []byte {
	file_sync_build_proto_rawDescOnce.Do(func() {
		file_sync_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_build_proto_rawDesc), len(file_sync_build_proto_rawDesc)))
	})
	return file_sync_build_proto_rawDescData
}

var file_sync_build_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sync_build_proto_goTypes = []any{
	(*WorkerConfig)(nil),      // 0: sync.WorkerConfig
	(*WorkerBuildOutput)(nil), // 1: sync.WorkerBuildOutput
	(*WorkerBuildError)(nil),  // 2: sync.WorkerBuildError
	(*pb.SyncRequest)(nil),    // 3: provider.SyncRequest
}
var file_sync_build_proto_depIdxs = []int32{
	3, // 0: sync.WorkerConfig.req:type_name -> provider.SyncRequest
	2, // 1: sync.WorkerBuildOutput.error:type_name -> sync.WorkerBuildError
	0, // 2: sync.WorkerBuilder.BuildRepository:input_type -> sync.WorkerConfig
	1, // 3: sync.WorkerBuilder.BuildRepository:output_type -> sync.WorkerBuildOutput
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sync_build_proto_init() }
func file_sync_build_proto_init() {
	if File_sync_build_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_build_proto_rawDesc), len(file_sync_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_build_proto_goTypes,
		DependencyIndexes: file_sync_build_proto_depIdxs,
		MessageInfos:      file_sync_build_proto_msgTypes,
	}.Build()
	File_sync_build_proto = out.File
	file_sync_build_proto_goTypes = nil
	file_sync_build_proto_depIdxs = nil
}
