// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sync/exec.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileExtractor_GetFilesByRegex_FullMethodName = "/sync.FileExtractor/GetFilesByRegex"
)

// FileExtractorClient is the client API for FileExtractor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileExtractorClient interface {
	GetFilesByRegex(ctx context.Context, in *TaskFileFinder, opts ...grpc.CallOption) (*FileList, error)
}

type fileExtractorClient struct {
	cc grpc.ClientConnInterface
}

func NewFileExtractorClient(cc grpc.ClientConnInterface) FileExtractorClient {
	return &fileExtractorClient{cc}
}

func (c *fileExtractorClient) GetFilesByRegex(ctx context.Context, in *TaskFileFinder, opts ...grpc.CallOption) (*FileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileList)
	err := c.cc.Invoke(ctx, FileExtractor_GetFilesByRegex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileExtractorServer is the server API for FileExtractor service.
// All implementations should embed UnimplementedFileExtractorServer
// for forward compatibility.
type FileExtractorServer interface {
	GetFilesByRegex(context.Context, *TaskFileFinder) (*FileList, error)
}

// UnimplementedFileExtractorServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileExtractorServer struct{}

func (UnimplementedFileExtractorServer) GetFilesByRegex(context.Context, *TaskFileFinder) (*FileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFilesByRegex not implemented")
}
func (UnimplementedFileExtractorServer) testEmbeddedByValue() {}

// UnsafeFileExtractorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileExtractorServer will
// result in compilation errors.
type UnsafeFileExtractorServer interface {
	mustEmbedUnimplementedFileExtractorServer()
}

func RegisterFileExtractorServer(s grpc.ServiceRegistrar, srv FileExtractorServer) {
	// If the following call pancis, it indicates UnimplementedFileExtractorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileExtractor_ServiceDesc, srv)
}

func _FileExtractor_GetFilesByRegex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFileFinder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileExtractorServer).GetFilesByRegex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileExtractor_GetFilesByRegex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileExtractorServer).GetFilesByRegex(ctx, req.(*TaskFileFinder))
	}
	return interceptor(ctx, in, info, handler)
}

// FileExtractor_ServiceDesc is the grpc.ServiceDesc for FileExtractor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileExtractor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.FileExtractor",
	HandlerType: (*FileExtractorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFilesByRegex",
			Handler:    _FileExtractor_GetFilesByRegex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sync/exec.proto",
}
